# PART 1

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/survey_results_public.csv")
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [3]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [4]:
df.shape #No. of rows and colums

(88883, 85)

In [5]:
df.info() #Dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              88883 non-null  int64
 1   MainBranch              88331 non-null  object
 2   Hobbyist                88883 non-null  object
 3   OpenSourcer             88883 non-null  object
 4   OpenSource              86842 non-null  object
 5   Employment              87181 non-null  object
 6   Country                 88751 non-null  object
 7   Student                 87014 non-null  object
 8   EdLevel                 86390 non-null  object
 9   UndergradMajor          75614 non-null  object
 10  EduOther                84260 non-null  object
 11  OrgSize                 71791 non-null  object
 12  DevType                 81335 non-null  object
 13  YearsCode               87938 non-null  object
 14  Age1stCode              87634 non-null  object
 15  YearsCodePro            74331 non-null  object
 16  CareerSat               72847 non-null  object
 17  JobSat                  70988 non-null  object
 18  MgrIdiot                61159 non-null  object
 19  MgrMoney                61157 non-null  object
 20  MgrWant                 61232 non-null  object
 21  JobSeek                 80555 non-null  object
 22  LastHireDate            79854 non-null  object
 23  LastInt                 67155 non-null  object
 24  FizzBuzz                71344 non-null  object
 25  JobFactors              79371 non-null  object
 26  ResumeUpdate            77877 non-null  object
 27  CurrencySymbol          71392 non-null  object
 28  CurrencyDesc            71392 non-null  object
 29  CompTotal               55945 non-null  float64
 30  CompFreq                63268 non-null  object
 31  ConvertedComp           55823 non-null  float64
 32  WorkWeekHrs             64503 non-null  float64
 33  WorkPlan                68914 non-null  object
 34  WorkChallenge           68141 non-null  object
 35  WorkRemote              70284 non-null  object
 36  WorkLoc                 70055 non-null  object
 37  ImpSyn                  71779 non-null  object
 38  CodeRev                 70390 non-null  object
 39  CodeRevHrs              49790 non-null  float64
 40  UnitTests               62668 non-null  object
 41  PurchaseHow             61108 non-null  object
 42  PurchaseWhat            62029 non-null  object
 43  LanguageWorkedWith      87569 non-null  object
 44  LanguageDesireNextYear  84088 non-null  object
 45  DatabaseWorkedWith      76026 non-null  object
 46  DatabaseDesireNextYear  69147 non-null  object
 47  PlatformWorkedWith      80714 non-null  object
 48  PlatformDesireNextYear  77443 non-null  object
 49  WebFrameWorkedWith      65022 non-null  object
 50  WebFrameDesireNextYear  62944 non-null  object
 51  MiscTechWorkedWith      59586 non-null  object
 52  MiscTechDesireNextYear  64511 non-null  object
 53  DevEnviron              87317 non-null  object
 54  OpSys                   87851 non-null  object
 55  Containers              85366 non-null  object
 56  BlockchainOrg           48175 non-null  object
 57  BlockchainIs            60165 non-null  object
 58  BetterLife              86269 non-null  object
 59  ITperson                87141 non-null  object
 60  OffOn                   86663 non-null  object
 61  SocialMedia             84437 non-null  object
 62  Extraversion            87305 non-null  object
 63  ScreenName              80486 non-null  object
 64  SOVisit1st              83877 non-null  object
 65  SOVisitFreq             88263 non-null  object
 66  SOVisitTo               88086 non-null  object
 67  SOFindAnswer            87816 non-null  object
 68  SOTimeSaved             86344 non-null  object
 69  SOHowMuchTime           68378 non-null  object
 70  SOAccount               87828 non-null  object
 71  SOPartFreq              74692 non-null  object
 72  SOJobs                  88066 non-null  object
 73  EntTeams                87841 non-null  object
 74  SOComm                  88131 non-null  object
 75  WelcomeChange           85855 non-null  object
 76  SONewContent            69560 non-null  object
 77  Age                     79210 non-null  float64
 78  Gender                  85406 non-null  object
 79  Trans                   83607 non-null  object
 80  Sexuality               76147 non-null  object
 81  Ethnicity               76668 non-null  object
 82  Dependents              83059 non-null  object
 83  SurveyLength            86984 non-null  object
 84  SurveyEase              87081 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 57.6+ MB

In [7]:
pd.set_option("display.max_columns", 85) #Setting the columns to display
pd.set_option("display.max_rows",  85) #Setting the maximum rows to display

In [8]:
schema_df = pd.read_csv("data/survey_results_schema.csv")

In [9]:
schema_df #See the meaning of the columns

                    Column                                       QuestionText
0               Respondent  Randomized respondent ID number (not in order ...
1               MainBranch  Which of the following options best describes ...
2                 Hobbyist                            Do you code as a hobby?
3              OpenSourcer        How often do you contribute to open source?
4               OpenSource  How do you feel about the quality of open sour...
5               Employment  Which of the following best describes your cur...
6                  Country          In which country do you currently reside?
7                  Student  Are you currently enrolled in a formal, degree...
8                  EdLevel  Which of the following best describes the high...
9           UndergradMajor  What was your main or most important field of ...
10                EduOther  Which of the following types of non-degree edu...
11                 OrgSize  Approximately how many people are employed by ...
12                 DevType  Which of the following describe you? Please se...
13               YearsCode  Including any education, how many years have y...
14              Age1stCode  At what age did you write your first line of c...
15            YearsCodePro  How many years have you coded professionally (...
16               CareerSat  Overall, how satisfied are you with your caree...
17                  JobSat  How satisfied are you with your current job? (...
18                MgrIdiot  How confident are you that your manager knows ...
19                MgrMoney  Do you believe that you need to be a manager t...
20                 MgrWant  Do you want to become a manager yourself in th...
21                 JobSeek  Which of the following best describes your cur...
22            LastHireDate  When was the last time that you took a job wit...
23                 LastInt  In your most recent successful job interview (...
24                FizzBuzz  Have you ever been asked to solve FizzBuzz in ...
25              JobFactors  Imagine that you are deciding between two job ...
26            ResumeUpdate  Think back to the last time you updated your r...
27          CurrencySymbol  Which currency do you use day-to-day? If your ...
28            CurrencyDesc  Which currency do you use day-to-day? If your ...
29               CompTotal  What is your current total compensation (salar...
30                CompFreq   Is that compensation weekly, monthly, or yearly?
31           ConvertedComp  Salary converted to annual USD salaries using ...
32             WorkWeekHrs   On average, how many hours per week do you work?
33                WorkPlan            How structured or planned is your work?
34           WorkChallenge  Of these options, what are your greatest chall...
35              WorkRemote                    How often do you work remotely?
36                 WorkLoc                    Where would you prefer to work?
37                  ImpSyn  For the specific work you do, and the years of...
38                 CodeRev           Do you review code as part of your work?
39              CodeRevHrs  On average, how many hours per week do you spe...
40               UnitTests  Does your company regularly employ unit tests ...
41             PurchaseHow  How does your company make decisions about pur...
42            PurchaseWhat  What level of influence do you, personally, ha...
43      LanguageWorkedWith  Which of the following programming, scripting,...
44  LanguageDesireNextYear  Which of the following programming, scripting,...
45      DatabaseWorkedWith  Which of the following database environments h...
46  DatabaseDesireNextYear  Which of the following database environments h...
47      PlatformWorkedWith  Which of the following platforms have you done...
48  PlatformDesireNextYear  Which of the following platforms have you done...
49      WebFrameWorkedWith  Which of the following web frameworks have you...
50  WebFrameDesireNextYear  Which of the following web frameworks have you...
51      MiscTechWorkedWith  Which of the following other frameworks, libra...
52  MiscTechDesireNextYear  Which of the following other frameworks, libra...
53              DevEnviron  Which development environment(s) do you use re...
54                   OpSys  What is the primary operating system in which ...
55              Containers  How do you use containers (Docker, Open Contai...
56           BlockchainOrg  How is your organization thinking about or imp...
57            BlockchainIs  Blockchain / cryptocurrency technology is prim...
58              BetterLife  Do you think people born today will have a bet...
59                ITperson   Are you the "IT support person" for your family?
60                   OffOn        Have you tried turning it off and on again?
61             SocialMedia        What social media site do you use the most?
62            Extraversion    Do you prefer online chat or IRL conversations?
63              ScreenName                               What do you call it?
64              SOVisit1st  To the best of your memory, when did you first...
65             SOVisitFreq  How frequently would you say you visit Stack O...
66               SOVisitTo  I visit Stack Overflow to... (check all that a...
67            SOFindAnswer  On average, how many times a week do you find ...
68             SOTimeSaved  Think back to the last time you solved a codin...
69           SOHowMuchTime  About how much time did you save? If you're no...
70               SOAccount              Do you have a Stack Overflow account?
71              SOPartFreq  How frequently would you say you participate i...
72                  SOJobs  Have you ever used or visited Stack Overflow J...
73                EntTeams  Have you ever used Stack Overflow for Enterpri...
74                  SOComm  Do you consider yourself a member of the Stack...
75           WelcomeChange  Compared to last year, how welcome do you feel...
76            SONewContent  Would you like to see any of the following on ...
77                     Age  What is your age (in years)? If you prefer not...
78                  Gender  Which of the following do you currently identi...
79                   Trans                    Do you identify as transgender?
80               Sexuality  Which of the following do you currently identi...
81               Ethnicity  Which of the following do you identify as? Ple...
82              Dependents  Do you have any dependents (e.g., children, el...
83            SurveyLength  How do you feel about the length of the survey...
84              SurveyEase  How easy or difficult was this survey to compl...

# PART 2(Selecting rows and columns)

In [10]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [17]:
df = pd.DataFrame(people) #Dict to Dataframe

In [18]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [19]:
df["email"] #Accessing colunmn email

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [20]:
type(df["email"]) #Series can be called as a rows of a single column 
#Data frame is a container of series objects

pandas.core.series.Series

In [25]:
data = df[['last', 'email']] #Printing two columns and this is a dataframe not a series 
data

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com

In [28]:
type(data) #Combination of two columns is a DataFrame

pandas.core.frame.DataFrame

In [29]:
df.columns #Prininting the mname of all columns

Index(['first', 'last', 'email'], dtype='object')

In [30]:
df.iloc[0] #printing first row

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: object

In [31]:
df.iloc[[0, 1]] #Getting multiple rows as a dataframe

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com

In [32]:
df.iloc[[0, 1], 2] #Printing the email column for the first two rows

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: object

In [33]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [43]:
df.loc[[0, 1], ["email", "last"]]

                     email     last
0  CoreyMSchafer@gmail.com  Schafer
1        JaneDoe@email.com      Doe

In [47]:
#Going back to original dataframe for further analysis
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [48]:
df["Hobbyist"]

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [49]:
df["Hobbyist"].value_counts() #Printing the counts of diff values in  column

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [52]:
df.loc[[0, 1, 2], "Hobbyist"] #print the value of hobbyist for first three rows

0    Yes
1     No
2    Yes
Name: Hobbyist, dtype: object

In [53]:
df.loc[[0, 1, 2], "Hobbyist": "Employment"] #Indexing based on the column names

,Hobbyist,OpenSourcer,OpenSource,Employment
0,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
1,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"
2,Yes,Never,The quality of OSS and closed source software ...,Employed full-time

# PART 3 (Indexes)

In [39]:
df

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [56]:
df["email"]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [34]:
df.set_index("email") #Setting the email column as the index as it is a uniqe vale for each entry

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [35]:
df #Pandas did'nt change the dataframe for that we have to use inplace argument

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [38]:
df.set_index("email", inplace = True) 
df

KeyError: "None of ['email'] are in the columns"

In [37]:
df.index #Indexes have been changed

Index(['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com'], dtype='object', name='email')

In [40]:
df.loc["CoreyMSchafer@gmail.com", "last"] #Accesing the last name by email

'Schafer'

In [41]:
df.loc[0] #error since indices have been changed to email

KeyError: 0

In [42]:
df.reset_index(inplace = True) #Resetting index back to the numeric values

In [43]:
df

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe

In [46]:
#Goinig back to the original dataframe
df.head()

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe

In [47]:
df = pd.read_csv("data/survey_results_public.csv", index_col = "Respondent")
# df.set_index("Respondent") can also be used to make Respondent as index
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [48]:
#Schema dataset
df = pd.read_csv("data/survey_results_schema.csv")

In [49]:
df.head()

        Column                                       QuestionText
0   Respondent  Randomized respondent ID number (not in order ...
1   MainBranch  Which of the following options best describes ...
2     Hobbyist                            Do you code as a hobby?
3  OpenSourcer        How often do you contribute to open source?
4   OpenSource  How do you feel about the quality of open sour...

In [50]:
df.set_index("Column", inplace = True) #Setting column as a index so that we can search it using loc command

In [57]:
df.loc["Respondent"] #Get the respondent row as we are indexing using column names

QuestionText    Randomized respondent ID number (not in order ...
Name: Respondent, dtype: object

In [58]:
df.loc["Respondent","QuestionText"]

'Randomized respondent ID number (not in order of survey response time)'

In [59]:
df.loc[["Respondent"]] # If we want a DataFrame as output

                                                 QuestionText
Column
Respondent  Randomized respondent ID number (not in order ...

In [64]:
df.sort_index(ascending = True, inplace = True) #Sorting according to the index

In [65]:
df.head()

                                                    QuestionText
Column
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
BetterLife     Do you think people born today will have a bet...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BlockchainOrg  How is your organization thinking about or imp...

# PART 4 (Filtering)

In [72]:
df = pd.DataFrame(people) #Loading the people dataframne
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [74]:
filt = df["last"] == "Doe"
type(filt) #This filter is a series object

pandas.core.series.Series

In [76]:
df[filt] #Applying filter to the dataframe

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [77]:
#also can be achieved using loc command 
df.loc[filt]

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [82]:
df.loc[filt, ['email','last','first']] #First number indicates the rows we want and the second nunmber indicates the columns

               email last first
1  JaneDoe@email.com  Doe  Jane
2  JohnDoe@email.com  Doe  John

In [83]:
filt1 = (df['last'] == 'Doe') & (df['first'] == 'John')

In [85]:
df.loc[filt1,['first', 'last', 'email']]

  first last              email
2  John  Doe  JohnDoe@email.com

In [86]:
filt2 = (df['last'] == 'Doe') | (df['first'] == 'John')

In [87]:
df.loc[filt2]

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [89]:
df.loc[~filt2] #Everything that is not in this filter

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com

In [90]:
#Back to main data

In [91]:
df = pd.read_csv("data/survey_results_public.csv")

In [92]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [93]:
high_salary = (df["ConvertedComp"] >70000 )
df[high_salary]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
5,6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,Taken an online course in programming or softw...,NaN,Data or business analyst;Data scientist or mac...,13,15,3,Very satisfied,Slightly satisfied,Very confident,No,Yes,I am not interested in new job opportunities,1-2 years ago,Write any code;Complete a take-home project;In...,No,Financial performance or funding status of the...,I heard about a job opportunity (from a recrui...,CAD,Canadian dollar,40000.0,Monthly,366420.0,15.00,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,A little above average,No,NaN,"Yes, it's not part of our process but the deve...",Not sure,I have little or no influence,Java;R;SQL,Python;Scala;SQL,MongoDB;PostgreSQL,PostgreSQL,Android;Google Cloud Platform;Linux;Windows,Android;Google Cloud Platform;Linux;Windows,NaN,NaN,Hadoop,Hadoop;Pandas;TensorFlow;Unity 3D,Android Studio;Eclipse;PyCharm;RStudio;Visual ...,Windows,I do not use containers,Not at all,NaN,No,Yes,No,YouTube,In real life (in person),Login,2011,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult
8,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Database administrator;Developer, back-end;Dev...",12,11,4,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Interview with people in peer r...,Yes,Financial performance or funding status of the...,I was preparing for a job search,NZD,New Zealand dollar,138000.0,Yearly,95179.0,32.00,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",12.0,"Yes, it's not part of our process but the deve...",Not sure,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Ru...,DynamoDB;PostgreSQL;SQLite,PostgreSQL;Redis;SQLite,AWS;Docker;Heroku;Linux;MacOS;Slack,AWS;Docker;Heroku;Linux;MacOS;Slack;Other(s):,Express;Ruby on Rails;Other(s):,Express;Ruby on Rails;Other(s):,Node.js;Unity 3D,Node.js,Vim,MacOS,Development;Testing;Production,Not at all,An irresponsible use of resources,No,SIGH,Yes,Twitter,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
12,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Data or business analyst;Database administrato...,17,11,8,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Complete a take-home project;Interview with pe...,Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,90000.0,Yearly,90000.0,40.00,There is a schedule and/or spec (made by me or...,"Meetings;Non-work commitments (parenting, scho...",All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Rust...,Couchbase;DynamoDB;Firebase;MySQL,Firebase;MySQL;Redis,Android;AWS;Docker;IBM Cloud or Watson;iOS;Lin...,Android;AWS;Docker;IBM Cloud or Watson;Linux;S...,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Express;Vue.js,Node.js;Xamarin,Node.js;TensorFlow,Vim;Visual Studio;Visual Studio Code;Xcode,Windows,Development;Testing;Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,In real life (in person),Username,2011,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
15,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",10,17,3,Very satisfied,Slightly satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",3-4 years ago,Interview with people in senior / management r...,Yes,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,GBP,Pound sterling,29000.0,Monthly,455352.0,40.00,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,A few days each month,Home,Average,No,NaN,"No, but I think we should",Developers and management have nearly equal in...,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,C#;HTML/CSS;JavaScript;TypeScript;WebAssembly;...,MongoDB;Microsoft SQL Server;MySQL,Elasticsearch;MongoDB;Microsoft SQL Server;SQLite,NaN,AWS;Google Cloud Platform;Microsoft Azure,Angular/Angular.js;ASP.NET;jQuery,Angular/Angular.js;ASP.NET;React.js,.NET;.NET Core;Node.js,.NET Core;Node.js;React Native,Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,A passing fad,No,SIGH,No,YouTube,Online,Username,2010,Multiple times per day,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
21,22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,NaN,Taken an online course in programming or softw...,"10,000 or more employees","Data or business analyst;Designer;Developer, b...",35,12,18,Slightly satisfied,Very dissatisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Financial perf...,I had a negative experience or interaction at ...,USD,United States dollar,103000.0,Yearly,103000.0,40.00,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,"Less than half the time, but at least one day ...",Home,Average,No,NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Elasticsearch;MySQL;Oracle;Redis,Elasticsearch;MySQL;Oracle;Redis,Docker;Linux;Raspberry Pi;Windows,Docker;Linux;Raspberry Pi;Windows,Angular/Angular.js;Ruby on Rails,Angular/Angular.js;Ruby on Rails,Node.js,Node.js,Sublime Text;Visual Studio;Visual Studio Code,Windows,"Outside of work, for personal projects",Not at all,NaN,Yes,Yes,Yes,Instagram,Online,Username,I don't remember,Daily or almost daily,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88323,88876,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;Developer, game or graphics",8,15,2,Very satisfied,Slightly satisfied,Somewhat confident,Yes,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard)",No,Office environment or company culture;Remote w...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,180000.0,Yearly,180000.0,40.00,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Time spe...,"Less than half the time, but at least one day ...",Office,Average,"Yes, because I see value in code review",3.0,"Yes, it's part of our process",Not sure,I have little or no influence,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,C#;Java;Kotlin;Scala,DynamoDB;MySQL,DynamoDB,AWS;Linux;MacOS;Windows,Android;AWS;iOS;Linux;MacOS;Windows,NaN,NaN,Apache Spark;Hadoop;.NET Core;Unity 3D,Apache Spark;CryEngine;Hadoop;.NET;.NET Core;T...,IntelliJ;Notepad++;PyCharm;Sublime Text;Vim;Vi...,MacOS,I do not use containers,NaN,A passing fad,Yes,SIGH,Yes,Reddit,Neither,UserID,2011,A few times per month or weekly,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, somewhat",A lot less welcome now than last year,NaN,23.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
88324,88877,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,500 to 999 employees,Data scientist or machine learning specialist;...,31,18,28,Very satisfied,Very satisfied,Very confident,Yes,Yes,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in senior / management r...,Yes,"Industry that I'd be working in;Languages, fra...",I heard about a job opportunity (from a recrui...,USD,United States dollar,239000.0,Weekly,2000000.0,45.00,There is a schedule and/or spec (made by me or...,Meetings;Not enough people for the workload,Less than once per month / Never,Office,Far above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have some influence,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,Bash/Shell/PowerShell;Clojure;HTML/CSS;Java;Ja...,Oracle,Oracle,Docker;iOS;Kubernetes;Linux;Slack;Windows;Othe...,Other(s):,Other(s):,Other(s):,Apache Spark,Apache Spark,Atom;Emacs;IntelliJ;IPython / Jupyter;PyCharm;...,Windows,Development;Testing;Production,Implementing cryptocurrency-based products,An irresponsible use of resources,Yes,Yes,No,Facebook,Online,Screen Name,NaN,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was much faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,48.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
88325,88878,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,20 to 99 employees,"Developer, back-end;Developer, front-end;Devel...",12,14,3,Very satisfied,Very satisfied,Very confident,Yes,Yes,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,130000.0,Yearly,130000.0,40.00,There is a schedule and/or spec (made by me or...,"Non-work commitments (parenting, school work, ...",A few days each month,Office,Far above average,"Yes, because I see value in code review",3.0,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have some influence,HTML/CSS;JavaScript;Scala;TypeScript,JavaScript;Rust;Scala;TypeScript,PostgreSQL,PostgreSQL,Slack,Slack,React.js;Other(s):,React.js;Other(s):,Node.js,Node.js,IntelliJ;Sublime Text;Visual Studio Code,MacOS,Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,Online,Username,2010,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Easy
88326,88879,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Finland,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",20 to 99 employees,"Developer, desktop or enterprise applications;...",17,16,7,Slightly satisfied,Neither satisfied nor dissatisfied,Not at all confident,Not sure,I am already a manager,"I’m not actively looking, but I am open to new...",More than 4 years ago,Complete a take-home project;Interview with pe...,No,"Languages, frameworks, and other technologies ...",I had a negative experience or interaction at ...,EUR,European Euro,6000.0,Monthly,82488.0,37.75,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,Less than once per month / Never,Home,Far above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,Bash/Shell/PowerShell;C++;Python,C++,NaN,NaN,Android;Linux;Windows,Linux;Windows,NaN,NaN,NaN,TensorFlow;Unity 3D;Unreal Engine,Android Studio;Notepad++;Vim;Visual Studio,Windows,I do not use containers,Not at all,A passing fad,Yes,NaN,NaN,YouTube,Neither,Username,I don't remember,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not at all",Not applicable - I did not use Stack Overflow ...,NaN,34.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
88329,88882,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Netherlands,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Participated in online coding competitions (e....,100 to 499 employees,Academic researcher;Database administrator;Dev...,10,15,8,Slightly dissatisfied,Very dissatisfied,Not at all confident,Yes,Yes,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Complete a take-home project;In...,No,Office environment or company culture;Remote w...,I had a negative experience or interaction at ...,EUR,European Euro,42768.0,Monthly,588012.0,40.00,There is a schedule and/or spec (made by me or...,Distracting work environment;Lack of support f...,Less than once per month / Never,Home,Far above average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Not sure,I have little or no influence,C#;HTML/CSS;Java;JavaScript;PHP;Python,C#;Java;JavaScript;PHP,MariaDB;PostgreSQL,MariaDB;PostgreSQL,Android;Arduino;Linux;Raspberry Pi;WordPress,Android;Arduino;Linux;Raspberry Pi;WordPress,jQuery;React.js,jQuery;React.js,Unity 3D,Unity 3D,Android Studio;IntelliJ;Notepad++;Vim;Visual S...,Linux-based,I do not use containers,Not at all,A passing fad,Yes,Yes,Yes,Instagram,Neither,Username,2009,A few times per week,Find answers to specific questions,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy

In [118]:
df.loc[high_salary, ['Country', 'LanguageWorkedWith', 'ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
5,Canada,Java;R;SQL,366420.0
8,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
12,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
15,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0
21,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
...,...,...,...
88323,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88324,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88325,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0
88326,Finland,Bash/Shell/PowerShell;C++;Python,82488.0
88329,Netherlands,C#;HTML/CSS;Java;JavaScript;PHP;Python,588012.0

In [124]:
countries = ['United States', 'India', 'United Kingdom', 'Canada', 'Germany']

In [125]:
filt = (df["Country"].isin(countries))

In [126]:
type(filt) #Filter is a series object as we need

pandas.core.series.Series

In [128]:
data = df.loc[filt,["Country"]]
data

              Country
0      United Kingdom
3       United States
5              Canada
7               India
9               India
...               ...
88859   United States
88863  United Kingdom
88864           India
88877   United States
88878          Canada

[45008 rows x 1 columns]

In [133]:
# Suppose we want to find out people that answered python for the language worked with answer
# how would you do it?

In [134]:
df['LanguageWorkedWith']

0                          HTML/CSS;Java;JavaScript;Python
1                                      C++;HTML/CSS;Python
2                                                 HTML/CSS
3                                      C;C++;C#;Python;SQL
4              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
                               ...
88878                        HTML/CSS;JavaScript;Other(s):
88879                                                  NaN
88880                                                  NaN
88881                                                  NaN
88882    Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
Name: LanguageWorkedWith, Length: 88883, dtype: object

In [ ]:
# Now we use string method contains() to achieve this result

In [139]:
filt = df['LanguageWorkedWith'].str.contains("Python", na =False)

In [141]:
#If we just print the filter we will get a series containing true false values
filt

0         True
1         True
2        False
3         True
4         True
         ...
88878    False
88879    False
88880    False
88881    False
88882    False
Name: LanguageWorkedWith, Length: 88883, dtype: bool

In [144]:
# When we apply filter to a dataframe pandas return only the rows with true values
# Like a mask on the original dataframe

In [145]:
df.loc[filt, 'LanguageWorkedWith']

0                          HTML/CSS;Java;JavaScript;Python
1                                      C++;HTML/CSS;Python
3                                      C;C++;C#;Python;SQL
4              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
7        Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
                               ...
88854    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
88860      Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):
88865      Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):
88872             C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
88876                           HTML/CSS;JavaScript;Python
Name: LanguageWorkedWith, Length: 36443, dtype: object

# PART 5 (Modifying data within DataFrames)

In [146]:
df = pd.DataFrame(people)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [147]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

### If we want to rename all the columns in our dataframe

In [150]:
#using assignment operator
df.columns = ['first_name', 'last_name', 'email']
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [151]:
# If we want to make a same change in all columns
# We use list comprehension
df.columns = [x.upper() for x in df.columns]
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [154]:
df.columns = [x.replace("_", " ") for x in df.columns]
df

  FIRST NAME LAST NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [155]:
df.columns = [x.replace(" ", "_") for x in df.columns]
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [156]:
df.columns = [x.lower() for x in df.columns]
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

### If we want to rename specific columns in our dataframe

In [158]:
# Hint : Use pandas rename method
df.rename(columns = {'first_name' : "first", 'last_name' : 'last'}, inplace =True)

In [159]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

## Updating single row in DataFrame

In [165]:
df.loc[2] = ['john', 'Smith', 'johnsmith@gmail.com']

In [166]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   john    Smith      johnsmith@gmail.com

In [167]:
# Changing some values in the seconfd row
df.loc[2, ['last', 'email']] = ['Doe', 'Johndoe@email.com']

In [168]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   john      Doe        Johndoe@email.com

In [183]:
# Changing a single value in DataFrame
df.loc[2,'email'] = 'john@emnail.com'

In [184]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   john      Doe          john@emnail.com

In [187]:
filt = df['email'] == 'john@emnail.com'

  first last            email
2  john  Doe  john@emnail.com

In [191]:
#now we grab the row using filter and assign the last name column of that row as Smith

In [192]:
df.loc[filt, 'last'] = 'Smith' 
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   john    Smith          john@emnail.com

## Updating multiple row in DataFrame

In [194]:
df['email'] = df['email'].str.lower() #updating all the email values

In [195]:
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   john    Smith          john@emnail.com

## Four methods to replace all the values:
```
1. apply()
2. map()
3. applymap()
4. replace()
```

### 1a. apply() on series object

In [200]:
df['email'].apply(len)

0    23
1    17
2    15
Name: email, dtype: int64

In [201]:
# Applying custom function 
def update_email(email):
    return email.upper()

In [202]:
df['email'].apply(update_email)

0    COREYMSCHAFER@GMAIL.COM
1          JANEDOE@EMAIL.COM
2            JOHN@EMNAIL.COM
Name: email, dtype: object

In [205]:
# To assign these values we will use assignment 
df['email'] = df['email'].apply(update_email)
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane      Doe        JANEDOE@EMAIL.COM
2   john    Smith          JOHN@EMNAIL.COM

In [206]:
#Using lambda function to convvert it back to lower case
df['email'] = df['email'].apply(lambda x: x.lower())
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   john    Smith          john@emnail.com

 ### 1b. apply() on dataframe object

In [208]:
df['email'].apply(len)

0    23
1    17
2    15
Name: email, dtype: int64

In [209]:
df.apply(len) #This applies len function to each series in the dataframe(first, last, email)

first    3
last     3
email    3
dtype: int64

In [211]:
len(df['email'])

3

In [213]:
df.apply(len, axis = 1) #Changing the axis it counts the length of row series objects

0    3
1    3
2    3
dtype: int64

In [215]:
print(df.loc[0]) 
len(df.loc[0])

first                      Corey
last                     Schafer
email    coreymschafer@gmail.com
Name: 0, dtype: object

3

In [222]:
df.apply(pd.Series.min)  # Applies on all the column series

first                      Corey
last                         Doe
email    coreymschafer@gmail.com
dtype: object

### 2.applymap()

In [223]:
# This works only on dataframe
# apllies the function to every individual element of a dataframe
df.applymap(len)

   first  last  email
0      5     7     23
1      4     3     17
2      4     5     15

In [224]:
df.applymap(str.lower)

   first     last                    email
0  corey  schafer  coreymschafer@gmail.com
1   jane      doe        janedoe@email.com
2   john    smith          john@emnail.com

### 3.map()

In [227]:
# This only works on a series object
df['first'].map({'Corey' : 'Chris', 'Jane' : 'Mary'})
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   john    Smith          john@emnail.com

In [228]:
# Here we see that the values that were'nt substituted take NaN values
# If we want to keep the other names intact then we use replace()

### 4.replace()

In [229]:
df['first'].replace({'Corey' : 'Chris', 'Jane' : 'Mary'})
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   john    Smith          john@emnail.com

In [230]:
#To change dataframe we can use assignment operator
#df['first'] = df['first'].replace({'Corey' : 'Chris', 'Jane' : 'Mary'})

In [231]:
# Moving to actual data
df = pd.read_csv("data/survey_results_public.csv")
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [232]:
df.rename(columns = {'ConvertedComp' : 'SalaryUSD'})

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [233]:
#Now that we see that appropriate changes have been  made
# We can solidify them using inplace
df.rename(columns = {'ConvertedComp' : 'SalaryUSD'}, inplace = True)

In [235]:
df['SalaryUSD']

0            NaN
1            NaN
2         8820.0
3        61000.0
4            NaN
          ...
88878        NaN
88879        NaN
88880        NaN
88881        NaN
88882        NaN
Name: SalaryUSD, Length: 88883, dtype: float64

In [237]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [239]:
# Now if we want to change Yes to true and No to False in Hobbyist 
# 1st method
def Boolean(word):
    if word == 'Yes':
        return True
    else:
        return False
df['Hobbyist'].apply(Boolean)

0         True
1        False
2         True
3        False
4         True
         ...
88878     True
88879    False
88880    False
88881    False
88882     True
Name: Hobbyist, Length: 88883, dtype: bool

In [241]:
# 2nd method using replace
df['Hobbyist'].replace({'Yes' : 'True', 'No' : 'False'})

0         True
1        False
2         True
3        False
4         True
         ...
88878     True
88879    False
88880    False
88881    False
88882     True
Name: Hobbyist, Length: 88883, dtype: object

# PART 6(Add and remove columns/rows frome DataFrame)

In [279]:
df = pd.DataFrame(people)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

## Combining two columns

In [260]:
df['full_name']  = df['first'] + ' ' + df['last']
df

   first     last                    email      full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

## Dropping columns in a dataframe

In [261]:
df.drop(columns = ['first', 'last'])

                     email      full_name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [262]:
# now we can use inplace 
df.drop(columns = ['first', 'last'], inplace = True)

In [263]:
df

                     email      full_name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [255]:
# Getting back the original dataframe
# 1st method(naive)
data = df['full_name'].str.split(' ')
data

0    [Corey, Schafer]
1         [Jane, Doe]
2         [John, Doe]
Name: full_name, dtype: object

In [258]:
for i in range(len(data)):
    df.loc[i, 'first'] = data[i][0]
    df.loc[i, 'last'] = data[i][1]
df.drop(columns = 'full_name', inplace =True)
df

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe

In [264]:
# 2nd method(Corey's using expand)
df['full_name'].str.split(' ', expand = True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [265]:
df[['first', 'last']] = df['full_name'].str.split(' ', expand = True)
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

## Adding a single row to a dataframe

In [268]:
# Using append()
df.append({
    'first': 'atharva',
    'last': 'inamdar',
    'email': 'athucool7@gmail.com',
    'full_name': 'atharva inamdar'
})
df

TypeError: Can only append a dict if ignore_index=True

In [272]:
df.append({
    'first': 'atharva',
    'last': 'inamdar',
    'email': 'athucool7@gmail.com',
    #'full_name': 'atharva inamdar'
}, ignore_index = True)

                     email      full_name    first     last
0  CoreyMSchafer@gmail.com  Corey Schafer    Corey  Schafer
1        JaneDoe@email.com       Jane Doe     Jane      Doe
2        JohnDoe@email.com       John Doe     John      Doe
3      athucool7@gmail.com            NaN  atharva  inamdar

In [275]:
# If we use append() the values which are not passed will be Nan as seen above

## Appnding one dataframe to another

In [276]:
people2 = {
    "first": ["Tony", 'Steve'], 
    "last": ["Stark", 'Rogers'], 
    "email": ["IronMan@gmail.com", 'Cap@email.com']
}

In [278]:
df2 = pd.DataFrame(people2)
df2

   first    last              email
0   Tony   Stark  IronMan@gmail.com
1  Steve  Rogers      Cap@email.com

In [280]:
df.append(df2, ignore_index = True)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Tony    Stark        IronMan@gmail.com
4  Steve   Rogers            Cap@email.com

In [285]:
#making actual changes we have to use assignment operator
dfc = df.append(df2, ignore_index = True)
dfc

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Tony    Stark        IronMan@gmail.com
4  Steve   Rogers            Cap@email.com

## Removing rows

In [286]:
dfc

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Tony    Stark        IronMan@gmail.com
4  Steve   Rogers            Cap@email.com

In [289]:
#Using index in drop()
dfc.drop(index = 4, inplace = True)

In [290]:
dfc

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Tony    Stark        IronMan@gmail.com

In [291]:
filt = dfc['last'] == 'Doe'
dfc.drop(index = dfc[filt].index, inplace = True)

In [292]:
dfc

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
3   Tony    Stark        IronMan@gmail.com

# PART 7(Sorting Data)

In [293]:
df = pd.DataFrame(people)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

## Sorting by a particular column

In [294]:
df.sort_values(by = 'last')

   first     last                    email
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
0  Corey  Schafer  CoreyMSchafer@gmail.com

In [296]:
df.sort_values(by = 'last', ascending = False)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

## Soring by multiple columns (in case of ties)

In [299]:
df.sort_values(by = ['last', 'first'], ascending = False, inplace = True)

In [300]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
2   John      Doe        JohnDoe@email.com
1   Jane      Doe        JaneDoe@email.com

In [307]:
# Adding a column containing duplicate last
df = df.append({
    'first': 'Adam',
    'last': 'Doe',
    'email': 'a.email.com'
}, ignore_index = True)

In [308]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   John      Doe        JohnDoe@email.com
2   Jane      Doe        JaneDoe@email.com
3   Adam      Doe              a.email.com

In [310]:
# Soring last by descending and first by ascending in case of tie
df.sort_values(by = ['last', 'first'], ascending = [False, True], inplace = True)

In [311]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
3   Adam      Doe              a.email.com
2   Jane      Doe        JaneDoe@email.com
1   John      Doe        JohnDoe@email.com

In [312]:
# Now if we want our original dataframe
df.sort_index()

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   John      Doe        JohnDoe@email.com
2   Jane      Doe        JaneDoe@email.com
3   Adam      Doe              a.email.com

## Sorting a series object from a dataframe

In [313]:
df['last'].sort_values()

3        Doe
2        Doe
1        Doe
0    Schafer
Name: last, dtype: object

In [314]:
# original data
df = pd.read_csv("data/survey_results_public.csv")
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [315]:
df.sort_values(by ='Country', inplace = True)

In [318]:
df['Country'].head(50)

39018    Afghanistan
62723    Afghanistan
85185    Afghanistan
50437    Afghanistan
88340    Afghanistan
88735    Afghanistan
6391     Afghanistan
39754    Afghanistan
88181    Afghanistan
48122    Afghanistan
10697    Afghanistan
62124    Afghanistan
49377    Afghanistan
32971    Afghanistan
60559    Afghanistan
85827    Afghanistan
88033    Afghanistan
28470    Afghanistan
719      Afghanistan
26189    Afghanistan
86394    Afghanistan
85293    Afghanistan
7056     Afghanistan
7323     Afghanistan
86551    Afghanistan
58390    Afghanistan
73920    Afghanistan
28877    Afghanistan
51525    Afghanistan
45562    Afghanistan
46807    Afghanistan
44123    Afghanistan
22327    Afghanistan
8112     Afghanistan
80423    Afghanistan
59184    Afghanistan
60185    Afghanistan
37571    Afghanistan
29560    Afghanistan
42832    Afghanistan
12253    Afghanistan
58082    Afghanistan
61770    Afghanistan
50172    Afghanistan
78326        Albania
57057        Albania
49431        Albania
41344        Albania
33177        Albania
6688         Albania
Name: Country, dtype: object

In [320]:
#Checking the salary
df[['Country', 'ConvertedComp']].head(50)

           Country  ConvertedComp
39018  Afghanistan        19152.0
62723  Afghanistan      1000000.0
85185  Afghanistan            NaN
50437  Afghanistan            NaN
88340  Afghanistan            NaN
88735  Afghanistan            NaN
6391   Afghanistan            NaN
39754  Afghanistan            NaN
88181  Afghanistan            NaN
48122  Afghanistan         4464.0
10697  Afghanistan         3996.0
62124  Afghanistan            NaN
49377  Afghanistan            NaN
32971  Afghanistan            NaN
60559  Afghanistan            NaN
85827  Afghanistan            NaN
88033  Afghanistan            NaN
28470  Afghanistan            0.0
719    Afghanistan            0.0
26189  Afghanistan            NaN
86394  Afghanistan            NaN
85293  Afghanistan            NaN
7056   Afghanistan        14364.0
7323   Afghanistan            NaN
86551  Afghanistan            NaN
58390  Afghanistan            NaN
73920  Afghanistan            NaN
28877  Afghanistan            NaN
51525  Afghanistan            NaN
45562  Afghanistan            NaN
46807  Afghanistan            NaN
44123  Afghanistan            NaN
22327  Afghanistan         7980.0
8112   Afghanistan         1596.0
80423  Afghanistan            NaN
59184  Afghanistan            NaN
60185  Afghanistan            NaN
37571  Afghanistan            NaN
29560  Afghanistan         1116.0
42832  Afghanistan            NaN
12253  Afghanistan            NaN
58082  Afghanistan        17556.0
61770  Afghanistan            NaN
50172  Afghanistan       153216.0
78326      Albania         4968.0
57057      Albania            NaN
49431      Albania            NaN
41344      Albania            NaN
33177      Albania            NaN
6688       Albania        60000.0

In [329]:
# Sorting by multiple columns
df.sort_values(by = ['Country', 'ConvertedComp'], ascending = [True, False], inplace = True)

In [330]:
df[['Country','ConvertedComp']]

           Country  ConvertedComp
62723  Afghanistan      1000000.0
50172  Afghanistan       153216.0
39018  Afghanistan        19152.0
58082  Afghanistan        17556.0
7056   Afghanistan        14364.0
...            ...            ...
88873          NaN            NaN
88874          NaN            NaN
88879          NaN            NaN
88880          NaN            NaN
88881          NaN            NaN

[88883 rows x 2 columns]

## Grabbing the higest/lowest data easily

In [334]:
# using nlargest() method 
df[['ConvertedComp', 'Country']].nlargest(10, columns = 'ConvertedComp')

       ConvertedComp      Country
25833      2000000.0       Canada
87353      2000000.0      Germany
21895      2000000.0        India
28080      2000000.0        India
72274      2000000.0        India
77665      2000000.0       Mexico
79701      2000000.0  Netherlands
51798      2000000.0         Peru
75088      2000000.0    Singapore
32056      2000000.0  Switzerland

In [335]:
df[['ConvertedComp', 'Country']].nsmallest(10, columns = 'ConvertedComp')

       ConvertedComp                 Country
28470            0.0             Afghanistan
719              0.0             Afghanistan
13760            0.0                 Algeria
40655            0.0                 Armenia
30447            0.0               Australia
68611            0.0               Australia
19235            0.0                 Austria
16126            0.0              Bangladesh
29184            0.0  Bosnia and Herzegovina
1678             0.0                  Brazil